#!/usr/bin/env python3
"""
Test 4: Linear Congruential Generator Recovery
If keys are generated by LCG: d[i+1] = (a * d[i] + c) mod m
Then from 3 consecutive solved keys we can recover a, c, m.

For consecutive puzzles #1-#70 we have 70 keys. If ANY three consecutive
unmasked values satisfy an LCG relation, we can predict all future keys.

The challenge: we only know d[i] mod 2^(i-1) (the masked low bits).
For higher puzzles, we know more bits.
"""

SOLVED_CONSEC = [
    (1, 0x1), (2, 0x3), (3, 0x7), (4, 0x8),
    (5, 0x15), (6, 0x31), (7, 0x4c), (8, 0xe0),
    (9, 0x1d3), (10, 0x202), (11, 0x483), (12, 0xa7b),
    (13, 0x1460), (14, 0x2930), (15, 0x68f3), (16, 0xc936),
    (17, 0x1764f), (18, 0x3080d), (19, 0x5749f), (20, 0xd2c55),
    (21, 0x1ba534), (22, 0x2de40f), (23, 0x556e52), (24, 0xdc2a04),
    (25, 0x1fa5ee5), (26, 0x340326e), (27, 0x6ac3875), (28, 0xd916ce8),
    (29, 0x17e2551e), (30, 0x3d94cd64), (31, 0x7d4fe747), (32, 0xb862a62e),
    (33, 0x1a96ca8d8), (34, 0x34a65911d), (35, 0x4aed21170), (36, 0x9de820a7c),
    (37, 0x1757756a93), (38, 0x22382facd0), (39, 0x4b5f8303e9), (40, 0xe9ae4933d6),
    (41, 0x153869acc5b), (42, 0x2a221c58d8f),
    (43, 0x6bd3b27c591), (44, 0xe02b35a358f),
    (45, 0x122fca143c05), (46, 0x2ec18388d544), (47, 0x6cd610b53cba),
    (48, 0xade6d7ce3b9b), (49, 0x174176b015f4d), (50, 0x22bd43c2e9354),
    (51, 0x75070a1a009d4), (52, 0xefae164cb9e3c), (53, 0x180788e47e326c),
    (54, 0x236fb6d5ad1f43), (55, 0x6abe1f9b67e114), (56, 0x9d18b63ac4ffdf),
    (57, 0x1eb25c90795d61c), (58, 0x2c675b852189a21), (59, 0x7496cbb87cab44f),
    (60, 0xfc07a1825367bbe), (61, 0x13c96a3742f64906), (62, 0x363d541eb611abee),
    (63, 0x7cce5efdaccf6808), (64, 0xf7051f27b09112d4),
    (65, 0x1a838b13505b26867), (66, 0x2832ed74f2b5e35ee),
    (67, 0x730fc235c1942c1ae), (68, 0xbebb3940cd0fc1491),
    (69, 0x101d83275fb2bc7e0c), (70, 0x349b84b6431a6c4ef1),
]

import math

print("=" * 70)
print("  TEST 4: LCG Recovery from Consecutive Keys")
print("=" * 70)

# Method 1: For high-bit-count puzzles (e.g., #64-#70), the masked key
# gives us many bits of the raw value. If d[i] follows an LCG, then:
#   d[i+1] - a*d[i] ≡ c (mod m)  for all i
# From 3 values: d1, d2, d3:
#   d2 = a*d1 + c (mod m)
#   d3 = a*d2 + c (mod m)
#   d3 - d2 = a*(d2 - d1) (mod m)
#   a = (d3 - d2) * inverse(d2 - d1, m) (mod m)

# But we don't know m or the full d values.
# For puzzles #64-#66 (consecutive), we know:
#   d[64] mod 2^63 = 0xf7051f27b09112d4 - 2^63 = 0x77051f27b09112d4
#   d[65] mod 2^64 = 0x1a838b13505b26867 - 2^64 = 0xa838b13505b26867
#   d[66] mod 2^65 = 0x2832ed74f2b5e35ee - 2^65 = 0x832ed74f2b5e35ee

# The raw d values are 256 bits. We know the lowest bits.

print("\n  --- Method 1: Test LCG on low bits of consecutive keys ---")
print("  Using puzzles #64, #65, #66 (know 63, 64, 65 bits respectively)\n")

# Extract the known low bits (key value minus the high bit)
triples = []
for i in range(len(SOLVED_CONSEC) - 2):
    n1, k1 = SOLVED_CONSEC[i]
    n2, k2 = SOLVED_CONSEC[i+1]
    n3, k3 = SOLVED_CONSEC[i+2]
    if n2 == n1 + 1 and n3 == n2 + 1:
        # Low bits of each key
        low1 = k1 - (1 << (n1 - 1))  # n1-1 known bits
        low2 = k2 - (1 << (n2 - 1))  # n2-1 known bits
        low3 = k3 - (1 << (n3 - 1))  # n3-1 known bits
        triples.append((n1, low1, n1-1, low2, n2-1, low3, n3-1))

# For LCG with modulus m = 2^k, we can test on the low bits
# If d[i+1] = a*d[i] + c mod 2^k, then the low j bits of d[i+1]
# depend only on the low j bits of d[i], a, and c.

print("  Testing for 32-bit LCG (m = 2^32):")
# We need: low32(d2) = a * low32(d1) + c mod 2^32
# From puzzles #33+ we have ≥32 known bits

test_pairs = []
for n1, k1 in SOLVED_CONSEC:
    if n1 >= 34:  # need at least 33 bits
        n2 = n1 + 1
        # Find n2 in solved
        for nn, kk in SOLVED_CONSEC:
            if nn == n2:
                d1_low32 = (k1 - (1 << (n1-1))) & 0xFFFFFFFF
                d2_low32 = (kk - (1 << (n2-1))) & 0xFFFFFFFF
                test_pairs.append((n1, d1_low32, d2_low32))
                break

if len(test_pairs) >= 3:
    # From first two pairs, try to recover a and c
    _, d1_0, d2_0 = test_pairs[0]
    _, d1_1, d2_1 = test_pairs[1]

    # d2_0 = a * d1_0 + c mod 2^32
    # d2_1 = a * d1_1 + c mod 2^32
    # d2_0 - d2_1 = a * (d1_0 - d1_1) mod 2^32

    diff_out = (d2_0 - d2_1) % (1 << 32)
    diff_in = (d1_0 - d1_1) % (1 << 32)

    # Need modular inverse of diff_in mod 2^32 (only exists if diff_in is odd)
    if diff_in % 2 == 1:
        a_candidate = (diff_out * pow(diff_in, -1, 1 << 32)) % (1 << 32)
        c_candidate = (d2_0 - a_candidate * d1_0) % (1 << 32)

        print(f"  Candidate a = 0x{a_candidate:08x}")
        print(f"  Candidate c = 0x{c_candidate:08x}")

        # Verify against ALL pairs
        verified = 0
        failed = 0
        for n1, d1, d2 in test_pairs:
            predicted = (a_candidate * d1 + c_candidate) % (1 << 32)
            if predicted == d2:
                verified += 1
            else:
                failed += 1
                if failed <= 5:
                    print(f"  #{n1}: FAIL predicted=0x{predicted:08x} actual=0x{d2:08x}")

        print(f"  32-bit LCG: {verified} verified, {failed} failed")
        if failed == 0:
            print("  *** 32-BIT LCG CONFIRMED! ***")
    else:
        print(f"  diff_in is even (0x{diff_in:08x}), trying GCD approach...")

# Method 2: Test for power-of-2 modulus LCG at various bit widths
print("\n  --- Method 2: Test LCG at various bit widths ---")
for bits in [16, 32, 48, 64]:
    mod = 1 << bits
    pairs_at_bits = []
    for n1, k1 in SOLVED_CONSEC:
        if n1 >= bits + 2:
            n2 = n1 + 1
            for nn, kk in SOLVED_CONSEC:
                if nn == n2:
                    d1 = (k1 - (1 << (n1-1))) & (mod - 1)
                    d2 = (kk - (1 << (n2-1))) & (mod - 1)
                    pairs_at_bits.append((n1, d1, d2))
                    break

    if len(pairs_at_bits) >= 3:
        _, d1_0, d2_0 = pairs_at_bits[0]
        _, d1_1, d2_1 = pairs_at_bits[1]

        diff_out = (d2_0 - d2_1) % mod
        diff_in = (d1_0 - d1_1) % mod

        if math.gcd(diff_in, mod) == 1:
            a = (diff_out * pow(diff_in, -1, mod)) % mod
            c = (d2_0 - a * d1_0) % mod

            ok = sum(1 for _, d1, d2 in pairs_at_bits if (a * d1 + c) % mod == d2)
            total = len(pairs_at_bits)
            status = "*** MATCH ***" if ok == total else ""
            print(f"  {bits:3d}-bit LCG: a=0x{a:x} c=0x{c:x} — {ok}/{total} {status}")
        else:
            print(f"  {bits:3d}-bit LCG: diff_in not invertible")
    else:
        print(f"  {bits:3d}-bit LCG: not enough pairs ({len(pairs_at_bits)})")

# Method 3: Check if d[i+1] / d[i] is approximately constant
print("\n  --- Method 3: Ratio consistency (multiplicative generator?) ---")
ratios = []
for i in range(len(SOLVED_CONSEC) - 1):
    n1, k1 = SOLVED_CONSEC[i]
    n2, k2 = SOLVED_CONSEC[i+1]
    if n2 == n1 + 1 and k1 > 0 and n1 >= 20:
        r = k2 / k1
        ratios.append((n1, r))

if ratios:
    r_vals = [r for _, r in ratios]
    mean_r = sum(r_vals) / len(r_vals)
    std_r = (sum((r - mean_r)**2 for r in r_vals) / len(r_vals)) ** 0.5
    cv = std_r / mean_r
    print(f"  Mean ratio: {mean_r:.6f}")
    print(f"  Std dev:    {std_r:.6f}")
    print(f"  CV:         {cv:.6f}")
    print(f"  (CV near 0 = multiplicative generator; CV ~ 0.577 = random)")
    if cv < 0.1:
        print("  *** LOW CV — possible multiplicative pattern! ***")
    else:
        print(f"  Ratio is too variable for multiplicative generator.")

print("\n" + "=" * 70)
print("  TEST 4 COMPLETE")
print("=" * 70)
