#!/usr/bin/env python3
"""
Test 8: PRNG Fingerprinting

Test whether the puzzle keys were generated by common PRNGs:
1. Mersenne Twister (Python random / C++ mt19937)
2. xorshift128+ (V8 JavaScript engine)
3. PCG family
4. Linear feedback shift registers

Key observation: For MT19937, consecutive 32-bit outputs have detectable
linear relationships in GF(2). If keys are built from MT outputs,
the 32-bit words within and across keys will show these relationships.

For puzzle #64-#70, we know 63-69 bits = 2+ full 32-bit words per key.
"""

SOLVED = [
    (1, 0x1), (2, 0x3), (3, 0x7), (4, 0x8),
    (5, 0x15), (6, 0x31), (7, 0x4c), (8, 0xe0),
    (9, 0x1d3), (10, 0x202), (11, 0x483), (12, 0xa7b),
    (13, 0x1460), (14, 0x2930), (15, 0x68f3), (16, 0xc936),
    (17, 0x1764f), (18, 0x3080d), (19, 0x5749f), (20, 0xd2c55),
    (21, 0x1ba534), (22, 0x2de40f), (23, 0x556e52), (24, 0xdc2a04),
    (25, 0x1fa5ee5), (26, 0x340326e), (27, 0x6ac3875), (28, 0xd916ce8),
    (29, 0x17e2551e), (30, 0x3d94cd64), (31, 0x7d4fe747), (32, 0xb862a62e),
    (33, 0x1a96ca8d8), (34, 0x34a65911d), (35, 0x4aed21170), (36, 0x9de820a7c),
    (37, 0x1757756a93), (38, 0x22382facd0), (39, 0x4b5f8303e9), (40, 0xe9ae4933d6),
    (41, 0x153869acc5b), (42, 0x2a221c58d8f),
    (43, 0x6bd3b27c591), (44, 0xe02b35a358f),
    (45, 0x122fca143c05), (46, 0x2ec18388d544), (47, 0x6cd610b53cba),
    (48, 0xade6d7ce3b9b), (49, 0x174176b015f4d), (50, 0x22bd43c2e9354),
    (51, 0x75070a1a009d4), (52, 0xefae164cb9e3c), (53, 0x180788e47e326c),
    (54, 0x236fb6d5ad1f43), (55, 0x6abe1f9b67e114), (56, 0x9d18b63ac4ffdf),
    (57, 0x1eb25c90795d61c), (58, 0x2c675b852189a21), (59, 0x7496cbb87cab44f),
    (60, 0xfc07a1825367bbe), (61, 0x13c96a3742f64906), (62, 0x363d541eb611abee),
    (63, 0x7cce5efdaccf6808), (64, 0xf7051f27b09112d4),
    (65, 0x1a838b13505b26867), (66, 0x2832ed74f2b5e35ee),
    (67, 0x730fc235c1942c1ae), (68, 0xbebb3940cd0fc1491),
    (69, 0x101d83275fb2bc7e0c), (70, 0x349b84b6431a6c4ef1),
]

print("=" * 70)
print("  TEST 8: PRNG Fingerprinting")
print("=" * 70)

# ── Part A: Extract 32-bit words from known key bits ──
print("\n  --- Part A: Extract 32-bit words from high-bit keys ---")
print("  For puzzle #n, we know (n-1) low bits of the raw 256-bit key.")
print("  Extracting complete 32-bit words (little-endian and big-endian).\n")

# The raw key d[n] has its low (n-1) bits equal to k[n] - 2^(n-1)
# and bit (n-1) is the leading 1 set by masking.
# Bits n and above are UNKNOWN.

words_le = {}  # {puzzle_num: [word0, word1, ...]} little-endian 32-bit words
words_be = {}  # big-endian interpretation

for n, k in SOLVED:
    if n < 33:
        continue  # need at least 32 known bits
    raw_low = k  # The key itself IS the low n bits (with bit n-1 = 1)
    # Actually: raw_low = k, and we know bits 0..(n-1)
    # Complete 32-bit words we can extract:
    num_complete_words = n // 32  # floor

    le_words = []
    be_words = []
    for w in range(num_complete_words):
        word = (raw_low >> (32 * w)) & 0xFFFFFFFF
        le_words.append(word)

    # For big-endian: the HIGHEST known bits are at position (n-1) down
    # But the 256-bit key's big-endian words are [byte0..byte3][byte4..byte7]...
    # We know the LOWEST bits, which are the LAST bytes in big-endian
    # So big-endian word 7 (last) = bits 0..31, word 6 = bits 32..63, etc.
    for w in range(num_complete_words):
        word = (raw_low >> (32 * w)) & 0xFFFFFFFF
        be_words.append(word)  # Same extraction, different interpretation

    words_le[n] = le_words
    if n >= 64:
        print(f"  Puzzle #{n}: {num_complete_words} complete 32-bit words")
        for i, w in enumerate(le_words):
            print(f"    word[{i}]: 0x{w:08x}")

# ── Part B: MT19937 tempering inverse test ──
print("\n  --- Part B: MT19937 tempering structure ---")
print("  MT19937 output: y = x ^ (x>>11); y ^= (y<<7)&0x9d2c5680;")
print("  y ^= (y<<15)&0xefc60000; y ^= (y>>18)")
print("  If outputs are from MT, we can untemper to get state words.\n")

def mt_untemper(y):
    """Reverse MT19937 tempering to get internal state word."""
    # Undo y ^= y >> 18
    y ^= y >> 18
    # Undo y ^= (y << 15) & 0xefc60000
    y ^= (y << 15) & 0xefc60000
    # Undo y ^= (y << 7) & 0x9d2c5680
    tmp = y
    tmp = y ^ ((tmp << 7) & 0x9d2c5680)
    tmp = y ^ ((tmp << 7) & 0x9d2c5680)
    tmp = y ^ ((tmp << 7) & 0x9d2c5680)
    tmp = y ^ ((tmp << 7) & 0x9d2c5680)
    y = tmp
    # Undo y ^= y >> 11
    tmp = y
    tmp = y ^ (tmp >> 11)
    y = y ^ (tmp >> 11)
    return y & 0xFFFFFFFF

def mt_temper(x):
    """Apply MT19937 tempering."""
    y = x
    y ^= y >> 11
    y ^= (y << 7) & 0x9d2c5680
    y ^= (y << 15) & 0xefc60000
    y ^= y >> 18
    return y & 0xFFFFFFFF

# Verify untemper is correct
for test_val in [0, 1, 0xdeadbeef, 0x12345678, 0xFFFFFFFF]:
    assert mt_untemper(mt_temper(test_val)) == test_val, f"Untemper failed for {test_val}"
print("  Untemper verification: PASSED")

# Extract state words from consecutive puzzles
# If d[i] = getrandbits(256), each key uses 8 MT words.
# Puzzle i uses MT words 8*(i-1) to 8*(i-1)+7.
# getrandbits(256) in Python: generates 8 words, combines big-endian
# word[0] provides bits 224-255, word[7] provides bits 0-31

# So for puzzle #n, if we know bits 0-31 of d[n], that's MT word index 8*(n-1)+7
# bits 32-63 = MT word index 8*(n-1)+6, etc.

print("\n  Untempered state words from puzzle keys:")
state_words = {}  # {mt_index: state_value}

for n, k in SOLVED:
    if n < 33:
        continue
    num_words = n // 32
    for w in range(num_words):
        output_word = (k >> (32 * w)) & 0xFFFFFFFF
        state_word = mt_untemper(output_word)
        # MT index: word w of key n = position 8*(n-1) + (7-w)  [big-endian]
        mt_idx = 8 * (n - 1) + (7 - w)
        state_words[mt_idx] = state_word

        if n == 64:
            print(f"  Key #{n} word[{w}] → MT[{mt_idx}]: "
                  f"output=0x{output_word:08x} state=0x{state_word:08x}")

print(f"\n  Total state words recovered: {len(state_words)}")
print(f"  MT19937 needs 624 consecutive state words to predict.")

# ── Part C: Check MT19937 recurrence on recovered state words ──
print("\n  --- Part C: Verify MT19937 recurrence ---")
print("  MT recurrence: s[i+624] = s[i+397] ^ twist(s[i], s[i+1])")
print("  twist(a,b) = ((a&0x80000000)|(b&0x7fffffff)) >> 1 ^ (b&1 ? 0x9908b0df : 0)")

def mt_twist(a, b):
    """MT19937 twist operation."""
    y = (a & 0x80000000) | (b & 0x7FFFFFFF)
    result = y >> 1
    if y & 1:
        result ^= 0x9908b0df
    return result

# Check all triples (i, i+1, i+397, i+624) where we have state words
checked = 0
matched = 0
mismatched = 0

sorted_indices = sorted(state_words.keys())
for idx in sorted_indices:
    # Check: s[idx] = s[idx-624+397] ^ twist(s[idx-624], s[idx-624+1])
    # i.e., s[idx] = s[idx-227] ^ twist(s[idx-624], s[idx-623])
    need = [idx - 227, idx - 624, idx - 623]
    if all(n in state_words for n in need):
        predicted = state_words[need[0]] ^ mt_twist(state_words[need[1]], state_words[need[2]])
        if predicted == state_words[idx]:
            matched += 1
        else:
            mismatched += 1
            if mismatched <= 3:
                print(f"  MT[{idx}]: predicted=0x{predicted:08x} actual=0x{state_words[idx]:08x} MISMATCH")
        checked += 1

    # Also check forward: s[idx+624] = s[idx+397] ^ twist(s[idx], s[idx+1])
    need_fwd = [idx + 397, idx, idx + 1]
    target_fwd = idx + 624
    if target_fwd in state_words and all(n in state_words for n in need_fwd):
        predicted = state_words[need_fwd[0]] ^ mt_twist(state_words[need_fwd[1]], state_words[need_fwd[2]])
        if predicted == state_words[target_fwd]:
            matched += 1
        else:
            mismatched += 1
        checked += 1

print(f"  Recurrence checks: {checked} total, {matched} matched, {mismatched} mismatched")
if checked == 0:
    print("  (No overlapping triples found — keys too sparse for MT recurrence check)")
    print(f"  Key indices span: {sorted_indices[0]} to {sorted_indices[-1]}")
    print(f"  Gap: {sorted_indices[-1] - sorted_indices[0]} (need 624 overlap)")
elif mismatched == 0 and matched > 0:
    print("  *** MT19937 RECURRENCE CONFIRMED! ***")
else:
    print("  MT19937 recurrence REJECTED.")

# ── Part D: xorshift128+ test ──
print("\n  --- Part D: xorshift128+ structure test ---")
print("  xorshift128+: s1 ^= s1<<23; s1 ^= s1>>17; s1 ^= s0; s1 ^= s0>>26")
print("  output = s0 + s1 (mod 2^64)")
print("  Testing on 64-bit words from consecutive keys.\n")

# Extract 64-bit words
words64 = {}
for n, k in SOLVED:
    if n < 65:
        continue
    num_words = n // 64
    for w in range(num_words):
        word = (k >> (64 * w)) & 0xFFFFFFFFFFFFFFFF
        words64[(n, w)] = word

print(f"  Extracted {len(words64)} 64-bit words from keys")

# For xorshift128+, if each key uses 4 consecutive 64-bit outputs:
# Key n uses outputs at positions 4*(n-1) to 4*(n-1)+3
# We need consecutive outputs to check the recurrence

# ── Part E: Bit correlation between consecutive keys ──
print("\n  --- Part E: Bit-level correlation between consecutive keys ---")
print("  For truly random keys, XOR of consecutive key bits should be ~50% ones.\n")

for bit_pos in range(32):
    ones = 0
    total = 0
    for i in range(len(SOLVED) - 1):
        n1, k1 = SOLVED[i]
        n2, k2 = SOLVED[i + 1]
        if n2 == n1 + 1 and n1 > bit_pos + 1 and n2 > bit_pos + 1:
            b1 = (k1 >> bit_pos) & 1
            b2 = (k2 >> bit_pos) & 1
            if b1 ^ b2:
                ones += 1
            total += 1
    if total > 10:
        pct = ones / total * 100
        flag = " ***" if abs(pct - 50) > 15 else ""
        if bit_pos < 8 or abs(pct - 50) > 10:
            print(f"  bit {bit_pos:2d}: XOR = {ones}/{total} = {pct:.1f}% ones{flag}")

# ── Part F: Autocorrelation of key bits ──
print("\n  --- Part F: Bit autocorrelation within keys ---")
print("  For each key, compute autocorrelation of its bit string.\n")

# For high-bit keys, check if there's bit-level periodicity
for n, k in SOLVED:
    if n < 40:
        continue
    bits = [(k >> b) & 1 for b in range(n)]
    mean = sum(bits) / len(bits)

    # Autocorrelation at various lags
    suspicious_lags = []
    for lag in [1, 2, 4, 8, 16, 32]:
        if lag >= len(bits) // 2:
            continue
        corr_sum = 0
        for i in range(len(bits) - lag):
            corr_sum += (bits[i] - mean) * (bits[i + lag] - mean)
        var = sum((b - mean) ** 2 for b in bits)
        if var > 0:
            autocorr = corr_sum / var
            if abs(autocorr) > 0.3:
                suspicious_lags.append((lag, autocorr))

    if suspicious_lags and n >= 60:
        print(f"  Key #{n}: suspicious autocorrelation at lags "
              f"{[(l, f'{a:.3f}') for l, a in suspicious_lags]}")

print("\n  (No output for a key = no suspicious autocorrelation)")

print("\n" + "=" * 70)
print("  TEST 8 COMPLETE")
print("=" * 70)
